---
- hosts: all
  tasks:
  - name: "Install prerequisites for Docker repository"
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

  - name: "Add Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: "Add Docker APT repository"
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable


  - name: "Install Docker"
    package:
      name: "docker-ce"
      state: "latest"

  - name: "Install Docker-compose"
    package:
      name: "docker-compose"
      state: "latest"

  - name: "Start Docker service"
    service:
      name: "docker"
      state: "started"
      enabled: "yes"

  - name: "Add user admin to docker group"
    user:
      name: "admin"
      groups: "docker"
      append: "yes"

  - name: "Install Git"
    package:
      name: "git"
      state: "latest"

  - name: "Install Make"
    package:
      name: "make"
      state: "latest"
...
